apiVersion: v1
kind: Namespace
metadata:
  name: teamspeak
---
apiVersion: v1
kind: Service
metadata:
  name: teamspeak
  namespace: teamspeak
  labels:
    run: teamspeak
spec:
  ports:
  - name: teamspeak-data-port
    port: 30033
    targetPort: teamspeak-data
    protocol: TCP
  - name: teamspeak-data-port2
    port: 10011
    targetPort: teamspeak-data2
    protocol: TCP
  - name: teamspeak-voice-port
    port: 9987
    targetPort: teamspeak-voice
    protocol: UDP
  selector:
    app: teamspeak
  externalIPs:
  - 149.56.134.165
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak
  namespace: teamspeak
  labels:
    app: teamspeak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamspeak
  template:
    metadata:
     labels:
       app: teamspeak
    spec:
      volumes:
      - name: ts3
        emptyDir: {}
      containers:
        - name: teamspeak
          image: teamspeak
          imagePullPolicy: Always
          volumeMounts:
          - name: ts3
            mountPath: /var/ts3server/
          ports:
          - name: teamspeak-voice
            containerPort: 9987
            hostPort: 9987
            protocol: UDP
          - name: teamspeak-data
            containerPort: 30033
            hostPort: 30033
          - name: teamspeak-data2
            containerPort: 10011
            hostPort: 10011
          env:
          - name: 'TS3SERVER_LICENSE'
            value: 'accept'
          - name: 'TS3SERVER_DB_PLUGIN'
            value: 'ts3db_mariadb'
          - name: 'TS3SERVER_DB_SQLCREATEPATH'
            value: 'create_mariadb'
          - name: 'TS3SERVER_DB_HOST'
            value: 'mysql-svc.teamspeak.svc.cluster.local'
          - name: 'TS3SERVER_DB_USER'
            value: 'root'
          - name: 'TS3SERVER_DB_PASSWORD'
            value: 'test'
          - name: 'TS3SERVER_DB_NAME'
            value: 'teamspeak'
          - name: 'TS3SERVER_DB_WAITUNTILREADY'
            value: '30'
      dnsPolicy: Default

