apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: teamspeak
  labels:
    run: mysql
spec:
  ports:
  - name: mysql-db-port
    port: 3306
    targetPort: mysql
    protocol: TCP
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: teamspeak
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
     labels:
       app: mysql
    spec:
      volumes:
      - name: mysql
        emptyDir: {}
      containers:
        - name: db
          image: mariadb
          env:
          - name: 'MYSQL_ROOT_PASSWORD'
            value: 'test'
          - name: 'MYSQL_DATABASE'
            value: 'teamspeak'
          ports:
          - name: mysql
            containerPort: 3306
            protocol: TCP
      dnsPolicy: Default

